 CREATE TABLE students (
                id INT AUTO_INCREMENT PRIMARY KEY,
                reg VARCHAR(264),
                name VARCHAR(264),
                dept VARCHAR(264),
                year VARCHAR(264),
                question1 INT,
                question2 INT,
                question3 INT,
                question4 INT,
                question5 INT,
                question6 INT,
                question7 INT,
                question8 INT,
                question9 INT,
                question10 INT,
                question11 INT,
                question12 INT,
                question13 INT,
                question14 INT,
                question15 INT,
                question16 INT,
                question17 INT,
                question18 INT,
                question19 INT,
                question20 INT
            )