# Generated by Django 4.1.5 on 2023-10-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reg', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('quota', models.CharField(max_length=255)),
                ('deptid', models.IntegerField()),
                ('yearid', models.CharField(max_length=5)),
                ('secid', models.CharField(max_length=255)),
                ('set1', models.CharField(max_length=255)),
                ('nos', models.IntegerField()),
                ('s1', models.CharField(max_length=10)),
                ('s2', models.CharField(max_length=10)),
                ('s3', models.CharField(max_length=10)),
                ('s4', models.CharField(max_length=10)),
                ('s5', models.CharField(max_length=10)),
                ('s6', models.CharField(max_length=10)),
                ('s7', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
